# Generated by Django 5.2.5 on 2025-09-11 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0006_alter_organization_slug'),
        ('people', '0001_initial_contact_and_loginuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_email', models.EmailField(help_text='Email address for billing notifications', max_length=254)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', help_text='Current status of the account', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag - when False, account is deactivated')),
                ('membership_number', models.CharField(help_text='Unique membership identifier across entire system', max_length=50, unique=True)),
                ('membership_type', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('honorary', 'Honorary'), ('lifetime', 'Lifetime Member')], default='student', help_text='Type of membership held by this member', max_length=50)),
                ('membership_start_date', models.DateField(help_text='Date when membership began')),
                ('membership_end_date', models.DateField(blank=True, help_text='Date when membership expires (null for indefinite)', null=True)),
                ('emergency_contact_name', models.CharField(help_text='Name of emergency contact', max_length=100)),
                ('emergency_contact_phone', models.CharField(help_text='Phone number for emergency contact', max_length=20)),
                ('emergency_contact_relationship', models.CharField(help_text='Relationship to member (parent, spouse, etc.)', max_length=50)),
                ('medical_conditions', models.TextField(blank=True, help_text='Any medical conditions relevant to training')),
                ('medical_clearance_date', models.DateField(blank=True, help_text='Date of last medical clearance (if required)', null=True)),
                ('billing_contact', models.ForeignKey(blank=True, help_text='Contact responsible for billing (optional, defaults to primary contact)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_billing_accounts', to='people.contact')),
                ('member_contact', models.OneToOneField(help_text='Contact information for this member (one-to-one relationship)', on_delete=django.db.models.deletion.CASCADE, related_name='member_account', to='people.contact')),
                ('primary_contact', models.ForeignKey(help_text='Primary contact for this account (required)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_primary_accounts', to='people.contact')),
            ],
            options={
                'verbose_name': 'Member Account',
                'verbose_name_plural': 'Member Accounts',
                'db_table': 'accounts_member_account',
            },
        ),
        migrations.CreateModel(
            name='MemberAccountContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('primary', 'Primary Contact'), ('billing', 'Billing Contact'), ('emergency', 'Emergency Contact'), ('member', 'Member'), ('guardian', 'Guardian')], default='member', max_length=50)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.memberaccount')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.contact')),
            ],
        ),
        migrations.AddField(
            model_name='memberaccount',
            name='contacts',
            field=models.ManyToManyField(help_text='All contacts associated with this member account', related_name='member_accounts', through='accounts.MemberAccountContact', to='people.contact'),
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_object_id', models.PositiveIntegerField(help_text='ID of the specific account instance')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount (positive for payments, negative for refunds)', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('payment_date', models.DateTimeField(help_text='When the payment was made/processed')),
                ('due_date', models.DateField(blank=True, help_text='When payment was/is due (for invoices)', null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('direct_debit', 'Direct Debit')], help_text='Method used for payment', max_length=50)),
                ('transaction_reference', models.CharField(blank=True, help_text='External transaction ID or reference', max_length=100)),
                ('processor_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee charged by payment processor', max_digits=8)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partial_refund', 'Partial Refund'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the payment', max_length=20)),
                ('payment_type', models.CharField(choices=[('membership_fee', 'Membership Fee'), ('grading_fee', 'Grading Fee'), ('equipment', 'Equipment Purchase'), ('event_fee', 'Event Fee'), ('subscription', 'Tenant Subscription'), ('late_fee', 'Late Payment Fee'), ('refund', 'Refund'), ('adjustment', 'Account Adjustment')], help_text='Category/purpose of the payment', max_length=50)),
                ('invoice_number', models.CharField(blank=True, help_text='Invoice number if applicable', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details about the payment')),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not visible to customer)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_content_type', models.ForeignKey(help_text='Type of account (TenantAccount or MemberAccount)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(help_text='User who created this payment record', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment History',
                'db_table': 'accounts_payment_history',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='TenantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_email', models.EmailField(help_text='Email address for billing notifications', max_length=254)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', help_text='Current status of the account', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag - when False, account is deactivated')),
                ('tenant_name', models.CharField(help_text='Organization name for this tenant', max_length=100)),
                ('tenant_slug', models.SlugField(help_text='URL-safe tenant identifier (unique across system)', max_length=100, unique=True)),
                ('tenant_domain', models.CharField(blank=True, help_text='Custom domain for tenant (optional)', max_length=100, null=True)),
                ('subscription_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', help_text='Subscription tier determining features and limits', max_length=50)),
                ('subscription_start_date', models.DateTimeField(help_text='When the subscription began')),
                ('subscription_end_date', models.DateTimeField(blank=True, help_text='When the subscription expires (null for indefinite)', null=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly subscription fee amount', max_digits=10)),
                ('max_member_accounts', models.PositiveIntegerField(default=100, help_text='Maximum number of member accounts allowed')),
                ('max_clubs', models.PositiveIntegerField(default=5, help_text='Maximum number of clubs allowed')),
                ('max_associations', models.PositiveIntegerField(default=1, help_text='Maximum number of associations allowed')),
                ('timezone', models.CharField(default='UTC', help_text='Default timezone for this tenant', max_length=50)),
                ('locale', models.CharField(default='en-US', help_text='Default locale for this tenant', max_length=10)),
                ('billing_contact', models.ForeignKey(blank=True, help_text='Contact responsible for billing (optional, defaults to primary contact)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_billing_accounts', to='people.contact')),
                ('organization', models.OneToOneField(blank=True, help_text='Associated django-organizations Organization', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('primary_contact', models.ForeignKey(help_text='Primary contact for this account (required)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_primary_accounts', to='people.contact')),
            ],
            options={
                'verbose_name': 'Tenant Account',
                'verbose_name_plural': 'Tenant Accounts',
                'db_table': 'accounts_tenant_account',
            },
        ),
        migrations.AddField(
            model_name='memberaccount',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this member account', on_delete=django.db.models.deletion.CASCADE, related_name='member_accounts', to='accounts.tenantaccount'),
        ),
        migrations.CreateModel(
            name='TenantAccountContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('primary', 'Primary Contact'), ('billing', 'Billing Contact'), ('emergency', 'Emergency Contact'), ('member', 'Member'), ('guardian', 'Guardian')], default='member', max_length=50)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenantaccount')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.contact')),
            ],
        ),
        migrations.AddField(
            model_name='tenantaccount',
            name='contacts',
            field=models.ManyToManyField(help_text='All contacts associated with this tenant account', related_name='tenant_accounts', through='accounts.TenantAccountContact', to='people.contact'),
        ),
        migrations.AddIndex(
            model_name='memberaccountcontact',
            index=models.Index(fields=['account', 'relationship_type'], name='acc_member_contact_rel_idx'),
        ),
        migrations.AddIndex(
            model_name='memberaccountcontact',
            index=models.Index(fields=['is_active'], name='acc_member_contact_act_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='memberaccountcontact',
            unique_together={('account', 'contact')},
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['account_content_type', 'account_object_id'], name='accounts_payment_account_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['payment_date'], name='accounts_payment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['payment_status'], name='accounts_payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['payment_type'], name='accounts_payment_type_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['invoice_number'], name='accounts_payment_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['transaction_reference'], name='accounts_payment_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='memberaccount',
            index=models.Index(fields=['tenant', 'membership_number'], name='accounts_member_tenant_num_idx'),
        ),
        migrations.AddIndex(
            model_name='memberaccount',
            index=models.Index(fields=['membership_type'], name='accounts_member_type_idx'),
        ),
        migrations.AddIndex(
            model_name='memberaccount',
            index=models.Index(fields=['membership_start_date'], name='accounts_member_start_idx'),
        ),
        migrations.AddIndex(
            model_name='memberaccount',
            index=models.Index(fields=['membership_end_date'], name='accounts_member_end_idx'),
        ),
        migrations.AddConstraint(
            model_name='memberaccount',
            constraint=models.UniqueConstraint(fields=('membership_number',), name='accounts_member_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='memberaccount',
            constraint=models.UniqueConstraint(fields=('member_contact',), name='accounts_member_contact_unique'),
        ),
        migrations.AddIndex(
            model_name='tenantaccountcontact',
            index=models.Index(fields=['account', 'relationship_type'], name='acc_tenant_contact_rel_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantaccountcontact',
            index=models.Index(fields=['is_active'], name='acc_tenant_contact_act_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantaccountcontact',
            unique_together={('account', 'contact')},
        ),
        migrations.AddIndex(
            model_name='tenantaccount',
            index=models.Index(fields=['tenant_slug'], name='accounts_tenant_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantaccount',
            index=models.Index(fields=['subscription_type'], name='accounts_tenant_sub_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantaccount',
            index=models.Index(fields=['subscription_end_date'], name='accounts_tenant_exp_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantaccount',
            constraint=models.UniqueConstraint(fields=('tenant_slug',), name='accounts_tenant_slug_unique'),
        ),
    ]
