# Generated by Django 5.2.5 on 2025-09-14 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial_account_hierarchy'),
        ('people', '0003_add_contact_organization_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaccount',
            name='primary_contact',
            field=models.ForeignKey(blank=True, help_text='Primary contact for this account (required - set after creation to avoid circular dependency)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_primary_accounts', to='people.contact'),
        ),
        migrations.AlterField(
            model_name='tenantaccount',
            name='primary_contact',
            field=models.ForeignKey(blank=True, help_text='Primary contact for this account (required - set after creation to avoid circular dependency)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_primary_accounts', to='people.contact'),
        ),
    ]
