# Generated by Django 5.2.5 on 2025-09-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_memberaccount_primary_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantaccount',
            name='organization',
        ),
    ]
