# Generated by Django 5.2.5 on 2025-09-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_tenant_organization_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberaccount',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='memberaccount',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='memberaccount',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='memberaccount',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='memberaccount',
            name='medical_clearance_date',
        ),
        migrations.RemoveField(
            model_name='memberaccount',
            name='medical_conditions',
        ),
        migrations.AlterField(
            model_name='tenantaccountcontact',
            name='relationship_type',
            field=models.CharField(choices=[('primary', 'Primary Contact'), ('billing', 'Billing Contact')], default='primary', max_length=50),
        ),
        migrations.DeleteModel(
            name='MemberAccountContact',
        ),
    ]
