# Generated by Django 5.2.5 on 2025-09-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_emergency_medical_fields'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaccount',
            name='clubs',
            field=models.ManyToManyField(blank=True, help_text='Clubs this member account is associated with', related_name='account_members', through='clubs.ClubMember', to='clubs.club'),
        ),
    ]
