# Generated by Django 5.2.5 on 2025-10-01 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_memberaccount_clubs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='memberaccount',
            name='accounts_member_number_unique',
        ),
        migrations.RemoveConstraint(
            model_name='memberaccount',
            name='accounts_member_contact_unique',
        ),
        migrations.RemoveConstraint(
            model_name='tenantaccount',
            name='accounts_tenant_slug_unique',
        ),
        migrations.RemoveIndex(
            model_name='tenantaccount',
            name='accounts_tenant_slug_idx',
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this payment record', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
