# Generated by Django 5.2.8 on 2025-11-26 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_memberaccount_accounts_member_number_unique_and_more'),
    ]

    operations = [
        # Rename the field from relationship_type to role
        migrations.RenameField(
            model_name='tenantaccountcontact',
            old_name='relationship_type',
            new_name='role',
        ),
        # The index will be automatically updated by Django when the field is renamed
    ]
