# Generated by Django 5.2.5 on 2025-09-17 11:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_remove_emergency_medical_fields'),
        ('organizations', '0006_alter_organization_slug'),
        ('people', '0004_add_emergency_medical_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.organization')),
                ('description', models.TextField(blank=True)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('facebook_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('youtube_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('linkedin_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('is_public', models.BooleanField(default=True)),
                ('max_members', models.PositiveIntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(help_text='Tenant for multi-tenant isolation', on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='accounts.tenantaccount')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'db_table': 'clubs_club',
                'ordering': ['name'],
            },
            bases=('organizations.organization',),
        ),
        migrations.CreateModel(
            name='ClubAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation_type', models.CharField(choices=[('branch', 'Branch Location'), ('partner', 'Partner Club'), ('association', 'Association Member')], default='partner', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('established_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club_primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations_as_primary', to='clubs.club')),
                ('club_secondary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations_as_secondary', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Club Affiliation',
                'verbose_name_plural': 'Club Affiliations',
                'db_table': 'clubs_clubaffiliation',
                'ordering': ['established_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending Approval')], default='active', max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Name of emergency contact', max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Phone number for emergency contact', max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, help_text='Relationship to member (parent, spouse, etc.)', max_length=50)),
                ('medical_conditions', models.TextField(blank=True, help_text='Any medical conditions relevant to training')),
                ('medical_clearance_date', models.DateField(blank=True, help_text='Date of last medical clearance (if required)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_accounts', to='clubs.club')),
                ('member_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='accounts.memberaccount')),
            ],
            options={
                'verbose_name': 'Club Member',
                'verbose_name_plural': 'Club Members',
                'db_table': 'clubs_clubmember',
                'ordering': ['joined_date'],
            },
        ),
        migrations.CreateModel(
            name='ClubStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('instructor', 'Instructor'), ('assistant', 'Assistant')], default='instructor', max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('specialties', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_manage_members', models.BooleanField(default=False)),
                ('can_manage_schedule', models.BooleanField(default=False)),
                ('can_view_finances', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_assignments', to='people.loginuser')),
            ],
            options={
                'verbose_name': 'Club Staff',
                'verbose_name_plural': 'Club Staff',
                'db_table': 'clubs_clubstaff',
                'ordering': ['role', 'assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['tenant'], name='clubs_club_tenant__450773_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['founded_date'], name='clubs_club_founded_3ed476_idx'),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.CheckConstraint(condition=models.Q(('max_members__gte', 1), ('max_members__isnull', True), _connector='OR'), name='positive_max_members'),
        ),
        migrations.AddIndex(
            model_name='clubaffiliation',
            index=models.Index(fields=['club_primary', 'is_active'], name='clubs_cluba_club_pr_aaed14_idx'),
        ),
        migrations.AddIndex(
            model_name='clubaffiliation',
            index=models.Index(fields=['affiliation_type'], name='clubs_cluba_affilia_f1e918_idx'),
        ),
        migrations.AddConstraint(
            model_name='clubaffiliation',
            constraint=models.UniqueConstraint(fields=('club_primary', 'club_secondary'), name='unique_club_affiliation'),
        ),
        migrations.AddConstraint(
            model_name='clubaffiliation',
            constraint=models.CheckConstraint(condition=models.Q(('club_primary', models.F('club_secondary')), _negated=True), name='no_self_affiliation'),
        ),
        migrations.AddIndex(
            model_name='clubmember',
            index=models.Index(fields=['club', 'status'], name='clubs_clubm_club_id_dba42d_idx'),
        ),
        migrations.AddIndex(
            model_name='clubmember',
            index=models.Index(fields=['member_account'], name='clubs_clubm_member__e17fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='clubmember',
            index=models.Index(fields=['membership_number'], name='clubs_clubm_members_db1c09_idx'),
        ),
        migrations.AddIndex(
            model_name='clubmember',
            index=models.Index(fields=['joined_date'], name='clubs_clubm_joined__433252_idx'),
        ),
        migrations.AddConstraint(
            model_name='clubmember',
            constraint=models.UniqueConstraint(fields=('club', 'member_account'), name='unique_member_per_club'),
        ),
        migrations.AddConstraint(
            model_name='clubmember',
            constraint=models.UniqueConstraint(condition=models.Q(('membership_number__gt', ''), ('membership_number__isnull', False)), fields=('club', 'membership_number'), name='unique_membership_number_per_club'),
        ),
        migrations.AddIndex(
            model_name='clubstaff',
            index=models.Index(fields=['club', 'is_active'], name='clubs_clubs_club_id_1a8f40_idx'),
        ),
        migrations.AddIndex(
            model_name='clubstaff',
            index=models.Index(fields=['user', 'is_active'], name='clubs_clubs_user_id_18f863_idx'),
        ),
        migrations.AddIndex(
            model_name='clubstaff',
            index=models.Index(fields=['role'], name='clubs_clubs_role_28b639_idx'),
        ),
        migrations.AddConstraint(
            model_name='clubstaff',
            constraint=models.UniqueConstraint(fields=('club', 'user'), name='unique_staff_assignment_per_club'),
        ),
    ]
