# Generated by Django 5.2.5 on 2025-09-21 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('organizations', '0006_alter_organization_slug'),
        ('people', '0004_add_emergency_medical_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubstaff',
            name='organization_user',
            field=models.OneToOneField(blank=True, help_text='Link to Organization User for django-organizations integration', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_staff_assignment', to='organizations.organizationuser'),
        ),
        migrations.AddIndex(
            model_name='clubstaff',
            index=models.Index(fields=['organization_user'], name='clubs_clubs_organiz_2dd47c_idx'),
        ),
    ]
