# Generated by Django 5.2.5 on 2025-09-24 23:33

from django.db import migrations


def add_club_name_uniqueness_constraint(apps, schema_editor):
    """
    Add unique constraint for club name per tenant.

    Since Club inherits from Organization via multi-table inheritance,
    we need to create a unique constraint across the join.
    For now, we rely on the model's clean() method for validation
    and document that a proper DB constraint would require a trigger
    or a custom approach depending on the database backend.
    """
    # For multi-table inheritance, Django doesn't provide a clean way
    # to create constraints across tables in the ORM.
    # The model's clean() method provides the validation.
    # A future enhancement could add database triggers for enforcement.
    pass


def remove_club_name_uniqueness_constraint(apps, schema_editor):
    """Remove the unique constraint (no-op since we're relying on model validation)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_add_organization_user_to_clubstaff'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.RunPython(
            add_club_name_uniqueness_constraint,
            remove_club_name_uniqueness_constraint
        ),
    ]
