# Generated by Django 5.2.8 on 2025-12-02 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_add_club_name_uniqueness_constraint'),
        ('people', '0005_rename_loginuser_to_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_assignments', to='people.userprofile'),
        ),
    ]
