# Generated by Django 5.2.5 on 2025-09-09 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, help_text="Person's first name", max_length=50)),
                ('last_name', models.CharField(db_index=True, help_text="Person's last name", max_length=50)),
                ('date_of_birth', models.DateField(help_text='Date of birth for age calculation and records')),
                ('address', models.TextField(help_text='Complete postal address')),
                ('mobile_number', models.CharField(help_text='Primary mobile phone number', max_length=20)),
                ('email', models.EmailField(db_index=True, help_text='Email address (must be unique)', max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='people_contact_name_idx'), models.Index(fields=['email'], name='people_contact_email_idx'), models.Index(fields=['is_active'], name='people_contact_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('email',), name='people_contact_email_unique')],
            },
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_club_owner', models.BooleanField(default=False, help_text='Can own and fully manage clubs')),
                ('is_club_staff', models.BooleanField(default=False, help_text='Can assist with club management')),
                ('permissions_level', models.CharField(choices=[('member', 'Member'), ('staff', 'Staff'), ('owner', 'Owner'), ('admin', 'Administrator')], default='member', help_text='General permission level for club operations', max_length=20)),
                ('can_create_clubs', models.BooleanField(default=False, help_text='Permission to create new clubs')),
                ('can_manage_members', models.BooleanField(default=False, help_text='Permission to manage club member rosters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_attempt', models.DateTimeField(blank=True, null=True)),
                ('contact', models.OneToOneField(help_text='Associated contact information', on_delete=django.db.models.deletion.CASCADE, related_name='login_user', to='people.contact')),
                ('user', models.OneToOneField(help_text='Django User account for authentication', on_delete=django.db.models.deletion.CASCADE, related_name='login_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login User',
                'verbose_name_plural': 'Login Users',
                'indexes': [models.Index(fields=['permissions_level'], name='people_loginuser_perm_idx'), models.Index(fields=['is_club_owner'], name='people_loginuser_owner_idx')],
            },
        ),
    ]
