# Generated by Django 5.2.5 on 2025-09-11 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial_account_hierarchy'),
        ('people', '0001_initial_contact_and_loginuser'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='people_contact_email_unique',
        ),
        migrations.AddField(
            model_name='contact',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this contact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people_contacts', to='accounts.tenantaccount'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, help_text='Email address (must be unique per tenant)', max_length=254),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant'], name='people_contact_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant', 'email'], name='people_contact_t_email_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='people_contact_tenant_email_unique'),
        ),
    ]
