# Generated by Django 5.2.5 on 2025-09-11 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial_account_hierarchy'),
        ('organizations', '0006_alter_organization_slug'),
        ('people', '0002_remove_contact_people_contact_email_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Direct organization membership', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people_contacts', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization'], name='people_contact_org_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'email'], name='people_contact_org_email_idx'),
        ),
    ]
