# Generated by Django 5.2.5 on 2025-09-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_add_contact_organization_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Name of emergency contact', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Phone number for emergency contact', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, help_text='Relationship to member (parent, spouse, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='medical_clearance_date',
            field=models.DateField(blank=True, help_text='Date of last medical clearance (if required)', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Any medical conditions relevant to training'),
        ),
    ]
