# Generated by Django 5.2.8 on 2025-12-02 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_add_emergency_medical_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='user',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_club_owner', models.BooleanField(default=False, help_text='Can own and fully manage clubs')),
                ('is_club_staff', models.BooleanField(default=False, help_text='Can assist with club management')),
                ('permissions_level', models.CharField(choices=[('member', 'Member'), ('staff', 'Staff'), ('owner', 'Owner'), ('admin', 'Administrator')], default='member', help_text='General permission level for club operations', max_length=20)),
                ('can_create_clubs', models.BooleanField(default=False, help_text='Permission to create new clubs')),
                ('can_manage_members', models.BooleanField(default=False, help_text='Permission to manage club member rosters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_attempt', models.DateTimeField(blank=True, null=True)),
                ('contact', models.OneToOneField(help_text='Associated contact information', on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='people.contact')),
                ('user', models.OneToOneField(help_text='Django User account for authentication', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
