# Generated by Django 5.2.8 on 2025-12-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_rename_loginuser_to_userprofile'),
        ('people', '0005_rename_loginuser_to_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginUser',
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['permissions_level'], name='people_loginuser_perm_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_club_owner'], name='people_loginuser_owner_idx'),
        ),
    ]
