# Generated by Django 5.2.8 on 2025-12-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_rename_loginuser_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_system_admin',
            field=models.BooleanField(default=False, help_text='System administrator with full tenant-wide access'),
        ),
    ]
