# Generated by Django 5.2.8 on 2025-12-02 04:12

from django.db import migrations


def migrate_permissions_forward(apps, schema_editor):
    UserProfile = apps.get_model('people', 'UserProfile')

    for user_profile in UserProfile.objects.all():
        level = user_profile.permissions_level

        if level == 'admin':
            user_profile.is_system_admin = True
            user_profile.can_create_clubs = True
            user_profile.can_manage_members = True
        elif level == 'owner':
            user_profile.is_system_admin = False
            user_profile.can_create_clubs = True
            user_profile.can_manage_members = True
        elif level == 'staff':
            user_profile.is_system_admin = False
            # Keep existing can_create_clubs value
            user_profile.can_manage_members = True
        # 'member' keeps defaults (all False)

        user_profile.save()


def migrate_permissions_reverse(apps, schema_editor):
    UserProfile = apps.get_model('people', 'UserProfile')

    for user_profile in UserProfile.objects.all():
        if user_profile.is_system_admin:
            user_profile.permissions_level = 'admin'
        elif user_profile.can_create_clubs and user_profile.can_manage_members:
            user_profile.permissions_level = 'owner'
        elif user_profile.can_manage_members:
            user_profile.permissions_level = 'staff'
        else:
            user_profile.permissions_level = 'member'

        user_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_add_is_system_admin_field'),
    ]

    operations = [
        migrations.RunPython(migrate_permissions_forward, migrate_permissions_reverse),
    ]
