# Generated by Django 5.2.8 on 2025-12-03 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_migrate_permissions_data'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='people_loginuser_perm_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_club_staff',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='permissions_level',
        ),
    ]
