# Generated by Django 5.2.8 on 2025-12-05 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_remove_deprecated_permission_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='people_loginuser_owner_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_club_owner',
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_system_admin'], name='people_userprofile_admin_idx'),
        ),
    ]
